<?xml version='1.0'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="b1_L" value="0.05" />
  <xacro:property name="b1_H" value="0.0015" />
  <xacro:property name="csupport_H" value="0.06863" />
  <xacro:property name="b2_H" value="0.050" />
  <xacro:property name="R_rueda" value="0.0245" />
  <xacro:property name="z" value="${csupport_H - (b2_H/2) - b1_H - R_rueda}" />

  <!-- Macro for castor wheel -->
  <xacro:macro name="castor_wheel" params="name origin_x">
    <!-- Castor wheel base (cube) -->
    <link name="${name}_b1_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${b1_L} ${b1_L} ${b1_H}" />
        </geometry>
        <material name="dark_gray" />
      </visual>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="0.028125" />
        <inertia ixx="5.864648437499999e-06" ixy="0" ixz="0"
            iyy="5.864648437499999e-06" iyz="0" izz="1.1718749999999999e-05" />
      </inertial>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.05 0.05 0.0015" />
        </geometry>
      </collision>
    </link>
    <joint name="${name}_b1_joint" type="fixed">
      <origin xyz="${origin_x} 0 -${b1_H / 2}" rpy="0 0 0" />
      <parent link="csupport_link" />
      <child link="${name}_b1_link" />
    </joint>

    <!-- Castor wheel base (cylinder) -->
    <link name="${name}_b2_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://romaa_description/meshes/romaa_castor_cylinder.stl" />
        </geometry>
        <material name="dark_gray" />
      </visual>
      <inertial>
        <origin xyz="0.0048464279113944195 0 0" rpy="0 0 0" />
        <mass value="0.03629327674887137" />
        <inertia ixx="1.2058314484155499e-05" ixy="0" ixz="0"
            iyy="9.601587537327375e-06" iyz="0" izz="6.537703376119888e-06" />
      </inertial>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder length="${b2_H}" radius="0.030" />
        </geometry>
      </collision>
    </link>
    <joint name="${name}_rot1_joint" type="continuous">
      <dynamics damping="0.0" friction="0.5" />
      <origin xyz="0 0 -${(b1_H/2) + (b2_H/2)}" rpy="0 0 0" />
      <parent link="${name}_b1_link" />
      <child link="${name}_b2_link" />
      <axis xyz="0 0 1" />
    </joint>

    <!-- Castor wheel -->
    <link name="${name}_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://romaa_description/meshes/romaa_castor_wheel.stl" />
        </geometry>
        <material name="light_gray" />
      </visual>
      <inertial>
        <origin xyz="0 0 0" rpy="${pi / 2} 0 0" />
        <mass value="0.0233673699785761" />
        <inertia ixx="4.260422817439314e-06" ixy="0" ixz="0"
            iyy="7.362120181084859e-06" iyz="0" izz="4.260422817439261e-06" />
      </inertial>
      <collision>
        <origin xyz="0 0 0" rpy="${pi / 2} 0 0" />
        <geometry>
          <cylinder length="0.016" radius="0.0245" />
        </geometry>
      </collision>
    </link>
    <joint name="${name}_rot2_joint" type="continuous">
      <dynamics damping="0.0" friction="0.5" />
      <origin xyz="-0.026 0 -${z}" rpy="0 0 0" />
      <parent link="${name}_b2_link" />
      <child link="${name}_link" />
      <axis xyz="0 1 0" />
    </joint>
  </xacro:macro>

</robot>
